### ISSUE TITLE
Binary build works, but not the build from the source code

### ISSUE THREAD

**Issue by gentoo-root** [LineageOS/android_device_oneplus_enchilada#3]
I'm trying to build a LineageOS for OnePlus 6, but unfortunately the device reboots immediately after the boot animation finishes. [The binary build](https://androidfilehost.com/?fid=1395089523397886208), however, boots successfully. I'm flashing LineageOS into a slot where the official OnePlus6Oxygen_22_OTA_028_all_1812250155_67229df34c11443b.zip was installed before, so the vendor image, radio and bootloader come from this firmware.

I saved a [logcat from the failing build](https://github.com/LineageOS/android_device_oneplus_enchilada/files/2923525/logcat-source.txt) by running logcat from /data/local/userinit.sh.

Is the binary firmware from androidfilehost built from the same sources? What could go wrong when building it from the source code?

**Comment by luk1337** [comment]
Extract blobs from binary build, not stock rom.

**Comment by luk1337** [comment]
....or use vendor repo from ~ very hidden ~ place that someone on IRC would probably tell you about lol.

**Comment by gentoo-root** [comment]
Thanks, it boots with the blobs from the binary build.
